name: Github CI
on:
  pull_request:
    branches:
      - '**'
  push:
    branches:
      - master
      - 'release/**'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 11.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Installtion of NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installation
        run: npm install
        env:
          CI: true
      - name: Build
        run: npm run build
        env:
          CI: true

  test:
    name: Unit tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 11.x]

    services:
      mongodb:
        image: mongo:latest
        env:
          MONGO_INITDB_DATABASE: bot
        ports:
          - 27017:27017

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Installtion of NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installation
        run: npm install
        env:
          CI: true
      - name: Running unit tests
        run: npm test
        env:
          CI: true
          DB_USER: user
          DB_PWD: pwd
          DB_NAME: bot
          GH_ACTIONS: true

  sonarCloud:
    name: SonarCloud
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [11.x]

    services:
      mongodb:
        image: mongo:latest
        env:
          MONGO_INITDB_DATABASE: tsouquet
        ports:
          - 27017:27017

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Installtion of NodeJS ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Installation
        run: npm install
        env:
          CI: true
      - name: Analysing & SonarCloud upload
        run: npm run sonar
        env:
          CI: true
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          DB_USER: user
          DB_PWD: pwd
          DB_NAME: bot
          GH_ACTIONS: true
